[build]
  publish = "test_backend"
  command = "echo 'Pas de build nécessaire'"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/*"
  to = "/in.html"
  status = 200